coverage:
  status:
    project:
      default: off
      tests:
        target: 100%
        flags: tests
      libswiftnav:
        flags: libswiftnav

flags:
  tests:
    paths: "tests/"
  libswiftnav:
    paths: "!tests/"

comment:
  layout: "diff, files, footer"
  behavior: default
  require_changes: no
