coverage:
  status:
    project:
      default: off
      tests:
        target: 100%
        paths: "tests/"
      libswiftnav:
        paths: "!tests/"

comment:
  layout: "diff, files, footer"
  behavior: default
  require_changes: no
